Крестики нолики
Coll4pse/C_PlusPlus_labs pull request #2
Opened 2020-03-30 18:15 UTC by Coll4pse

2020-03-31 19:17 UTC, Toxin65 requested changes
Общие принципы вы неплохо поняли, идентификаторы имеют осмысленные имена, всё в общем хорошо. Но забываете методы делать const и обработка корня мне не нравится из за большого количества узкоспециализированного кода. + не нравится подсчёт исходов игры в массиве, где непонятно какой элемент за что отвечает, если не читать код, надо бы его заменить на struct. Прошу внести изменения и причесать код, всё почти идеально.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +// Created by Михаил on 28.03.2020.
Михаил который... Надо же фамилию то писать.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +#include "PlayField.h"
Этот обычно первым ставится.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +            setY(y);
Сеттеры не стоит вызывать в конструкторе. Лучше напрямую инициализировать переменные. Но у вас там ассерты, так что ОК.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +        int getX() { return  m_x;}
А чего метод не const? Тут и ниже.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +        CellPos() = default;
Вы раз им нигде не пользуетесь и не подразумеваете его использование, надо сделать ему delete вместо default. Можно в public секции...

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +        int m_x, m_y;
Инициализация по-умолчанию -- это хороший тон. Лучше написать.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +    std::vector<CellPos*> getEmptyCells() const;
А зачем передавать указатели на CellPos? Просто массив экземпляров CellPos.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +            cells[i][j] = csEmpty;
Вы здесь инициализацию то сделали, но кто этот конструктор вызывает???

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +PlayField::CellStatus PlayField::operator[](CellPos *pos) const {
А почему CellPos передаётся по указателю, да ещё и не const???

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +PlayField PlayField::operator+(PlayField::CellPos *pos) const {
Тот же вопрос.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +            newField.cells[i][j] = cells[i][j];
В природе есть конструктор копирования. Так делать не надо.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +    newField.cells[(*pos).getX()][(*pos).getY()] = getEmptyCells().size() % 2 == 0 ? csNought : csCross;
`getEmptyCells().size() % 2`
Это интересный подход, правда он не спасает от инвалидных случаев... Но мысль хороша.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +                result.push_back(new CellPos(i, j));
Это просто ужасно! А кто их потом удалять будет? Каждому new должен быть свой delete. Но тут так делать не надо, просто экземпляры запихивайте в вектор...

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +                case csEmpty:
А это можно не обрабатывать... Зачем?

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +    (cells[0][2] == cells[1][1] && cells[1][1] == cells[2][0])) && cells[1][1] != csEmpty)
`cells[1][1] != csEmpty`
С этого надо начинать условие, чтобы всё остальное не считать...

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +}
Вроде правильно написано... Вы проверяли как работает?

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +    return this->operator+(pos);
`(*this)+pos;` же!

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +    CellStatus cells[3][3];
Неплохо.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.h
> +    void addChild(PlayField::CellPos pos);
Не соответствует ТЗ.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.h
> +    const PlayField::FieldStatus value();
Не соответствует ТЗ.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.h
> +    int childCount();
Почему не const?

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.h
> +    std::vector<PlayField::CellPos*> getEmptyCells();
Почему не const?

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.h
> +    TreeNode *previousNode;
Обычно именуют parent... Это же не двусвязный список, а дерево...

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.h
> +    std::vector<TreeNode*> nextNodes;
Тут, соответственно, обычно именуют children

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.h
> +    int childQty();
Почему не const?

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.h
> +    const PlayField playField;
Принято сначала методы писать, потом поля.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.h
> +    TreeNode(TreeNode *previous, PlayField playField);
Почему он в private? Вроде по ТЗ должен быть public.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +TreeNode::TreeNode(): playField(PlayField()){
`: playField(PlayField())` не нужно. Он и так будет инициализирован конструктором по-умолчанию.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +    previousNode = nullptr;
Это решается инициализацией поля по-умолчанию. Тут это не нужно, даже вредно.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +    previousNode = previous;
Можно так же как `playField` инициализировать. Но синтаксически и принципиально верно...

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +    return childQty() == 0 && childCount() == 0;
Ну нет. Признак терминала -- это окончание игры, а не количество потомков. Мы не хотим достраивать ветки, которые уже являются оконченной игрой.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +    return value() == PlayField::fsNormal ? (int)playField.getEmptyCells().size() - childCount() : 0;
Плохая идея. Суть в общем количестве, а не оставшемся. Не соответствует ТЗ,
Если нет родителя -- 9. Если есть родитель -- спросить у него `childQty()` и вычесть 1.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +    auto newNode = new TreeNode(this, playField.makeMove(&pos));
Ну тут будет переделано. Но по текущей реализации вопрос. А кто уничтожать то будет? new есть, а delete нет...

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +    return *nextNodes.at(index);
Зачем at, когда есть оператор[]

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +const PlayField::FieldStatus TreeNode::value() {
Не соответствует ТЗ. Надо поле возвращать, я не его статус.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +std::vector<PlayField::CellPos*> TreeNode::getEmptyCells() {
Не соответствует ТЗ. Такого метода по ТЗ нет.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +void inspectTree(TreeNode& node, int (&results)[3]) {
`int (&results)[3]` неплохо. Только непонятно что есть что, если ну читать весь код... Лучше бы завести под это дело struct. Тогда и возвращать его можно будет.

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +                assert(false);
Неплохо!

2020-03-31 19:17 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +    }
Не очень элегантно это всё... Лучше бы общий метод, который заполнит дерево, и, если хотите, сразу по нему прогуляется. Или второй метод после заполнения, который прогуляется и посчитает... Много специализированного кода получилось...

2020-04-03 10:39 UTC, Coll4pse commented on NoughtsAndCrosses/PlayField.cpp
> +                case csEmpty:
Ну чтоб узнать кто победил, как иначе?

2020-04-03 11:08 UTC, Coll4pse commented on NoughtsAndCrosses/TreeNode.h
> +    void addChild(PlayField::CellPos pos);
Можно конкретнее, пожалуйста

2020-04-05 16:57 UTC, Toxin65 requested changes
Мне бы хотелось видеть определённые изменения...
В общем всё неплохо. Стало лучше!

2020-04-05 16:57 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +    newField.cells[pos.getX()][pos.getY()] = getEmptyCells().size() % 2 == 0 ? csNought : csCross;
`getEmptyCells().size() % 2` это плохой критерий, если поле испорчено... Надо бы отдельный метод сделать...
К тому же следует проверять, что ячейка, куда делают ход пуста... Иначе будет ошибка.

2020-04-05 16:57 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +    CellStatus operator[](CellPos pos) const;
const :)
И ниже...

2020-04-05 16:57 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +    return value().checkFieldStatus() != PlayField::fsNormal;
Опираетесь на свойство enuma, но забываете, что если его кто-то расширит, то ваше условие может оказаться неверным. Поэтому следует явно проверять либо это победа, либо ничья.
И неплохо бы assert-нуться в случае fsInvalid

2020-04-05 16:57 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +    return parent == nullptr ? 9 : parent->childQty() - 1;
Тернарный оператор рекомендуется в скобочки ставить. И можно чуть проще, но спорно лучше ли:
`return (parent ? parent->childQty()-1 : 9);`

2020-04-05 16:57 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
> +    children.push_back(child);
Тут сразу можно child-у назначить parent-а. Чтобы не делать это незнамо где.

2020-04-05 16:57 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.cpp
>  TreeNode& TreeNode::operator[](int index) {
Что-то я только сейчас подумал, а он ведь const...

2020-04-05 16:57 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +void inspectTree(TreeNode& node, Score &score) {
Так стало более красиво!

2020-04-05 16:57 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +        TreeNode child = TreeNode(&node, node.value().makeMove(emptyPoses[i]));
Так делать нельзя. child будет уничтожен при выходе из блока у ближайшего }
Тут надо new использовать... А потом желательно подумать о его судьбе и в нужном деструкторе убить...

2020-04-05 16:57 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +    std::cout << "Ничьих: " << score[2] << std::endl;
Эти индексы.... Вы всё же к ним привыкли....
Ладно, общий уровень кода неплох. Но эти индексы, всё же нечитабельны... Хотя тут явно и указано, что есть что, но связи со структурой нет.

2020-04-05 16:57 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +    }
Всё же makeMove и здесь, и в inspectTree... А тут вообще main()... Некрасиво...

2020-04-05 16:57 UTC, Toxin65 commented on NoughtsAndCrosses/Score.h
> +    int operator[](int index){
Он же const...
Я вижу, вы сохранили совместимость с предыдущим кодом... Это неплохо. Правда более читабельными те места не стали... Но идея хороша.

2020-04-08 11:59 UTC, Coll4pse commented on NoughtsAndCrosses/PlayField.cpp
> +    newField.cells[pos.getX()][pos.getY()] = getEmptyCells().size() % 2 == 0 ? csNought : csCross;
Проверка на испорченость и пустоту клетки происходит в методе makeMove. makeMove единственный кто вызывает этот метод (оператор).

2020-04-08 13:00 UTC, Toxin65 requested changes
Недопоняли с new delete...

2020-04-08 13:00 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +    newField.cells[pos.getX()][pos.getY()] = getEmptyCells().size() % 2 == 0 ? csNought : csCross;
> makeMove единственный кто вызывает этот метод (оператор)

Это пока что так. Пока вы один программист в проекте.

2020-04-08 13:00 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +    CellStatus cells[3][3] = {csEmpty};
Это вы одну ячейку инициализировали. А надо все 9.

2020-04-08 13:00 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +        delete child;
Ничоси! А зачем его тут удалять. Пусть этим дерево занимается... Теперь он часть дерева.

2020-04-08 13:00 UTC, Toxin65 commented on NoughtsAndCrosses/TreeNode.h
Деструктора так и не появилось... А надо. Надо при уничтожении узла вызывать уничтожение всех потомков.

2020-04-08 13:00 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +        delete child;
То же. Говорил уже.

2020-04-08 15:32 UTC, Coll4pse commented on NoughtsAndCrosses/PlayField.cpp
> +    Player nextMovedPlayer = pNotInitialized;
В хедере комментарии оставил, поясняющие зачем добавил это.

2020-04-08 16:00 UTC, Toxin65 requested changes
Исправить замечания. Убрать лишний перечислитель.

2020-04-08 16:00 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +    };
Этот enum излишний. Он полностью дублирует CellStatus.

2020-04-08 16:00 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +    switch (this->movedPlayer){
Зачем писать this->???

2020-04-08 16:00 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +    auto newField = PlayField(*this, nextMovedPlayer);
Ну вообще, ещё и в конструкторе следующий ход передавать!
Напишите метод nextMove, который по состоянию поля определяет следующего ходящего.

2020-04-08 16:00 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +                cells[i][j] = copiedPF[CellPos(i, j)];
Для этого есть конструктор копирования по-умолчанию.

2020-04-08 20:39 UTC, Toxin65 requested changes
NoughtsAndCrosses/.gitignore не нужен, вроде как... Он один в корне лежит. Больше не надо.
Ну и немного замечаний осталось исправить... А в общем всё хорошо.

2020-04-08 20:39 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +                case csEmpty:
Но там break, т.е. ничего не происходит... И ниже такая же петрушка.

2020-04-08 20:39 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +                continue;
Это не нужно... Оно и так продолжит без этой ветки else...

2020-04-08 20:39 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +        return csCross;
Это условие нужно выпилить. Ниже условие полностью данное условие выполняет.

2020-04-08 20:39 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +        }
Вообще, он уже достаточно большой для вынесения в cpp...
Тогда и `#include <cassert>` в cpp переедет.

2020-04-08 20:39 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.h
> +    CellStatus operator[](CellPos pos) const;
Где мой const?

2020-04-08 20:39 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +    for (int i = 0; i < 9; i++) {
Уже тогда `i < startPoses.size()`

2020-04-08 20:39 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +        Score score = Score();
Зачем так сложно... Просто `Score score;`
Это и так будет конструктор по-умолчанию.

2020-04-09 10:49 UTC, Coll4pse commented on NoughtsAndCrosses/PlayField.cpp
> +                case csEmpty:
Ааа, так вы имели в виду именно csEmpty

2020-04-10 18:31 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +                case csEmpty:
Конечно.

2020-04-10 20:02 UTC, Toxin65 approved these changes
Выглядит неплохо. Если исправите -- будет ещё лучше. Успехов!

2020-04-10 20:02 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +int PlayField::CellPos::getY() const { return m_y; }
Я не против. Но однострочные можно в заголовочнике оставить...

2020-04-10 20:02 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +
Тут можно было не пропускать строку... Нет смысла.

2020-04-10 20:02 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +    auto newField = PlayField(*this);
Так не обязательно, даже излишне. Вы создаёте экземпляр, и тут же его копируете и уничтожаете. Можно сделать проще: `PlayField newField(*this);`
Но то, что вы используете auto -- неплохо.

2020-04-10 20:02 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +    for (int i = 0; i < 3; i++)
`3`, конечно выглядит как magic value. Можно бы его вынести внутрь класса в constexpr... Не настаиваю.

2020-04-10 20:02 UTC, Toxin65 commented on NoughtsAndCrosses/PlayField.cpp
> +    assert(checkFieldStatus() == fsNormal || (*this)[pos] == csEmpty);
Условие неправильное...

2020-04-10 20:02 UTC, Toxin65 commented on NoughtsAndCrosses/main.cpp
> +        node.addChild(child);
Можно сразу `node.addChild(new TreeNode(node.value().makeMove(emptyPoses[i])));`

2020-04-16 14:25 UTC, merged