Crosses and noughts bot edition
Coll4pse/C_PlusPlus_labs pull request #5
Opened 2020-04-30 15:16 UTC by Coll4pse

2020-05-05 15:11 UTC, Toxin65 requested changes
Вам ещё есть что поправить. Но начало было захватывающим, думал так до конца и прочитаю без комментариев...

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/PlayField.cpp
> +                result.emplace_back(i, j);
Молодца!

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/PlayField.cpp
> +        cells[1][1] == csCross ? isCrossWin = true : isNoughtWin = true;
Нуууу... Это можно было циклом сделать.... (((
Опять же привязка к константе появилась и magic value

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/PlayField.cpp
> +        || (*this)[pos] == csEmpty);
Условие мне не нравится... Почему там || ? Не достаточно просто проверять на пустоту?
К тому же часть этого ассерта повторяется в nextMove.
Считаю надо условие пересмотреть. Я с ним не согласен.

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/PlayField.cpp
> +    assert(status != fsInvalid && status != fsNoughtsWin && status != fsCrossesWin && status != fsDraw);
А может тут нужен только Normal???
Не согласен с текущим условием. Опять пляшем от обратного.

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/PlayField.cpp
> +    return (crossesCount - noughtsCount == 0 ? csCross : csNought);
Строго говоря, надо бы этот кусок сделать обособленным. Т.е. проверка строго на 0 и стого на 1, иначе падать.
Не стоит полагаться на внешний код, там тоже могут быть ошибки.

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/Score.h
> +    void operator+(const Score otherScore) {
Ой вэй... С каких это пор operator+ меняет содержимое и является не констовым?
Вы уж тогда пишите operator+=
Ведь когда вы пишите A=B+C вы не ожидаете, что B поменяется, верно? (кстати, если B будет const, то это защитит вас от отстрела конечности с таким как у вас оператором)

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/Score.h
> +};
Вообще голый заголовок без соответствующего cpp -- это не дело... Лучше сделать его частью чего-то. Да хоть в main прописать.

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/TreeNode.h
> +    const PlayField playField = PlayField();
```suggestion
    const PlayField playField;
```

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/TreeNode.cpp
> +    return (parent ? parent->childQty()-1 : 9);
Вообще говоря, 9 -- производная величина. А то опять magic value.

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/XOPlayer.h
> +    XOPlayer(TreeNode& tree, PlayField::CellStatus player): currentNode(&tree), player(player),
Не соответствует ТЗ.

> Определить для класса конструктор, принимающий на вход ссылку на построенное дерево решений (копии делать не надо, храним ссылку!)

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/XOPlayer.h
> +    std::vector<PlayField::CellPos> playerMoves;
А зачем?

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/XOPlayer.cpp
> +            currentNode = &child;
Вы так вольно переходите от указателя к ссылке и обратно, что становится немного жутко. Так обычно не поступают...

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/XOPlayer.cpp
> +        TreeNode& child = (*currentNode)[i];
А тут вы получаете указатель и делаете из него ссылку. Так делать непринято, потому что указатель может быть и нулевой, строго говоря. А ссылка обязана иметь нормальный экзмепляр под собой.

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/XOPlayer.cpp
> +    currentNode = maxChildren[rand() % maxChildren.size()];
Это круто!

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/XOPlayer.cpp
> +        if (sum > maxSum) {
У нас критерий изменился. В конференции сегодня написал... Надо переделать.
Сумма не важна -- важна доля от общих исходов.

2020-05-05 15:11 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/main.cpp
> +    for (int i = 0; i < emptyPoses.size(); i++)
```suggestion
    for (auto pos : emptyPoses)
```

2020-05-05 15:23 UTC, Coll4pse commented on NoughtsAndCrossesBotEdition/PlayField.cpp
> +    assert(status != fsInvalid && status != fsNoughtsWin && status != fsCrossesWin && status != fsDraw);
Но... Вы же сами говорили нельзя полагаться на enum. Я еще когда была лаба, где только дерево решений крестиков-ноликов построить, как раз проверял здесь на fsNormal, но вы сказали изменить...

2020-05-05 15:27 UTC, Coll4pse commented on NoughtsAndCrossesBotEdition/XOPlayer.h
> +    XOPlayer(TreeNode& tree, PlayField::CellStatus player): currentNode(&tree), player(player),
Но в файлике с тз, в main конструируется принимая 2 аргумента. Мне седлать 2 конструктора, один будет принимать только ссылку, а 2ой два аргумента и вызывать 1ый?

2020-05-05 16:46 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/XOPlayer.h
> +    XOPlayer(TreeNode& tree, PlayField::CellStatus player): currentNode(&tree), player(player),
` (копии делать не надо, храним ссылку!)`
**ссылку**

2020-05-06 11:36 UTC, Coll4pse commented on NoughtsAndCrossesBotEdition/XOPlayer.cpp
> +        TreeNode& child = (*currentNode)[i];
Так вроде нет же... Я разименовываю указатель на TreeNode, а там уже определен оператор [ ], который дите возвращает, в виде ссылки

2020-05-06 11:38 UTC, Coll4pse commented on NoughtsAndCrossesBotEdition/XOPlayer.h
> +    XOPlayer(TreeNode& tree, PlayField::CellStatus player): currentNode(&tree), player(player),
Ну я принимаю по ссылке, а храню в виде указателя, не ссылка, но и не копия же. Я б хранил по ссылке, но я изменяю это поле.

2020-05-06 11:46 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/XOPlayer.h
> +    XOPlayer(TreeNode& tree, PlayField::CellStatus player): currentNode(&tree), player(player),
**храним ссылку**
Можете себе любое другое поле сделать... Но обязаны хранить ссылку на дерево.

2020-05-06 11:47 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/XOPlayer.cpp
> +        TreeNode& child = (*currentNode)[i];
Да. Согласен. Я ошибся.

2020-05-06 11:53 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/PlayField.cpp
> +    assert(status != fsInvalid && status != fsNoughtsWin && status != fsCrossesWin && status != fsDraw);
Искал, не нашёл... Если можно -- процитируйте.
Я точно говорил, что при определении терминальной вершины надо проверять чей-то выигрышь, либо ничью.
Но в данном случае, ход возможен только при fsNormal. Хотя в тот раз я этого в данном месте кода не заметил. Но суть замечания такая же как и по определению терминала.

2020-05-06 12:11 UTC, Coll4pse commented on NoughtsAndCrossesBotEdition/XOPlayer.h
> +    std::vector<PlayField::CellPos> playerMoves;
Так уж реализовано, что если игрок напишет ячейку в которую он уже ходил, то в итоге выберется первая свободная ячейка для хода игрока, а так могу отлавливать

2020-05-06 12:15 UTC, Coll4pse commented on NoughtsAndCrossesBotEdition/PlayField.cpp
> +    assert(status != fsInvalid && status != fsNoughtsWin && status != fsCrossesWin && status != fsDraw);
https://github.com/Coll4pse/C_PlusPlus_labs/pull/2#discussion_r406915176

2020-05-06 12:24 UTC, Coll4pse commented on NoughtsAndCrossesBotEdition/main.cpp
> +    for (int i = 0; i < emptyPoses.size(); i++)
Я думал так сделать, но там мне важно i, чтоб рекурсивно дочерние ноды исследовать

2020-05-06 13:35 UTC, Coll4pse commented on NoughtsAndCrossesBotEdition/XOPlayer.h
> +    std::vector<PlayField::CellPos> playerMoves;
Придумал как исправить

2020-05-07 10:49 UTC, Toxin65 approved these changes
Ящитаю это Победа!

2020-05-07 10:49 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/PlayField.cpp
> +    for (int i = 1, j = 1; i < fieldDim; i++, j--) {
Эта пять :) А чё одним не обойтись?

2020-05-07 10:49 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/PlayField.cpp
> +    else
Можно без else, чтобы не запутывать...
Ещё есть вариент assert написать до if. У Кохновца такой вариант есть красивый.

2020-05-07 10:49 UTC, Toxin65 commented on NoughtsAndCrossesBotEdition/XOPlayer.cpp
> +        TreeNode* child = &(*currentNode)[i];
Блин, зря я вас сгоношил... Нормально всё было! :)
Я просто ошибся при чтении `(*currentNode)[i]`

2020-05-18 14:23 UTC, merged